### PR TITLE
Add a configurable relogin delay.

### LINKED ISSUE #11: Feature request: wait before trying to re-login
It would be nice to have a configurabile delay between login requests so that we can use the mobile app in a pinch while the MQTT gateway is running.

### PR DESCRIPTION
**Pull request by nanomad**
Add a new configurable setting to add a delay between login requests to the SAIC API.

This implements and fixes #11

### CODE REVIEW

**Comment by tosate** [comment]
Thank you for your contribution, but I don't think your code implements your requirement. At least it might have some side effects.
Almost every request needs to to be sent multiple times. This is because the car needs to wake up before it can provide data (if it's not running or charging). If the login credentials are expired in the meantime, a re-login is required. Combining this re-login with a delay will potentially slow down everything.
I think what you are trying to achieve has already been implemented in the Java version. Is this how it's done in Java?

**Comment by nanomad** [comment]
The Java API or MQTT gateway never implemented such feature. Right now SAIC API tokens never actually expire. In fact one could sniff the same used by the mobile app and use it for another client, avoiding any disconnections. So the only scenario of having to do a re-login is when the app gets opened, invalidating the current session. 

I know it's a work-around and probably not the prettiest one, but right now without a cooldown is basically impossibile to use gateway while traveling (since the app allows you to start remote cooling, stop charing and set charging limits).

I have revised the PR bringing the default cooldown value to 0 so that the behaviour is backwards compatibile and shouldn't cause any unwanted side effects.

**Comment by tosate** [comment]
Sorry, I didn't had time yet to take care about this. In addition, I am planning to refactor stuff. All this special logic related to waiting and retrying should go into the python-saic-client so that the applications that use it don't have to bother with this stuff.

Did you already test your code changes? What are your experiences so far?

**Comment by nanomad** [comment]
> Sorry, I didn't had time yet to take care about this. In addition, I am planning to refactor stuff. All this special logic related to waiting and retrying should go into the python-saic-client so that the applications that use it don't have to bother with this stuff.
> 
Makes sense :)

> Did you already test your code changes? What are your experiences so far?

I've been running my latest commit since yesterday. Works fine with a 15 minutes delay as it allows me to use the app in a pinch while not loosing too much data in the process. I'll probably try with a lower timeout (e.g. 5 minutes).

**Comment by nanomad** [comment]
Superseded by new implementation on develop

**Pull request closed without merging**
