### PR TITLE
Add suffix to battery heating stop reason topic to allow discriminate it from battery heating topic

### PR DESCRIPTION
**Pull request by pakozm**
I do not know exactly how to prepare this pull request, it is very simple.

### CODE REVIEW

**Comment by pakozm** [comment]
@nanomad This is a very simple fix, let me know if it can be integrated.

**Comment by pakozm** [comment]
@nanomad do you think this pull request can be added to master? Should I request it to `develop` branch?

**Comment by pakozm** [comment]
> @nanomad do you think this pull request can be added to master? Should I request it to `develop` branch?

Perfect, I move it to develop

**Comment by nanomad** [comment]
Hi @pakozm I'm sorry but I don't understand the request, the topic is used to publish and react to new battery heating schedules. Can you point where the error reason is actually published to this topic?

**Comment by pakozm** [comment]
> Hi @pakozm I'm sorry but I don't understand the request, the topic is used to publish and react to new battery heating schedules. Can you point where the error reason is actually published to this topic?

I'm sorry, I made a big mistake in the proposal. My purpose was to allow two different topics for the battery heating and the battery hearing stop reason. If not, the battery heating topic ends up with a weird "UNKNOWN (0)" or similar value, which is confusing. It should be, IMO, an ON or OFF value. So, having that value in the stop reason topic seems better, IMO.

I hope you find this time it much better.

**Review by nanomad — APPROVED** [review]

**Comment by nanomad** [comment]
Ah of course!

That was a big oversight from my side

**Pull request merged**
