### PR TITLE
Fix crash during message parsing (and other small fixes)

### LINKED ISSUE #11: Feature request: wait before trying to re-login
It would be nice to have a configurabile delay between login requests so that we can use the mobile app in a pinch while the MQTT gateway is running.

### PR DESCRIPTION
**Pull request by nanomad**
Included fixes:
- Relogin delay is not parsed as a number when set from env variabile
- There's a wrong type translation of Message to SaicMessage since that has been moved into the core client library
- The application kept running even if one of the core tasks crashed, making It impossible to restart via docker, Kubernetes, etc.
- Exception logging made it difficult to see where the application was crashing

This closes #11

### CODE REVIEW

**Comment by nanomad** [comment]
Rebased on top of develop. Remaining fixes:

- There's a wrong type translation of Message to SaicMessage since that has been moved into the core client library
- The application kept running even if one of the core tasks crashed, making It impossible to restart via docker, Kubernetes, etc.
- Exception logging made it difficult to see where the application was crashing

**Comment by nanomad** [comment]
This fixes #22

**Comment by tosate** [comment]
Thank you very much for your contribution. I had a busy week at work, so I couldn't have a look earlier.
You say: _There's a wrong type translation of Message to SaicMessage since that has been moved into the core client library_
I don't find where this is fixed in [61abb87](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/pull/21/commits/61abb872fe7e90feeef9b1a77f4cf31f73af6416).

**Comment by tosate** [comment]
It's the message = convert(msg) that you have already fixed in [530fb42](https://github.com/SAIC-iSmart-API/saic-python-mqtt-gateway/pull/21/commits/530fb4291d485bbab1c5a87086e78b9120518c8a), right?

**Comment by Tonno87** [comment]
Thank's goes to @nanomad.

**Pull request merged**
