### PR TITLE
Feature/control charge current limit

### PR DESCRIPTION
**Pull request by magior**
Added topic drivetrain/chargeCurrentLimit to set and handle charge current limit.

### CODE REVIEW

**Comment by tosate** [comment]
Hi @magior 

thank you for your contribution. This is to limit the current during charging?

Why is this limit a parameter in the set_target_battery_soc() method?
`self.saic_api.set_target_battery_soc(self.vehicle_state.target_soc, self.vin_info, charge_current_limit)`

In the current saic-python-client implementation, the parameter charge_current_limit is not known. It should be an optional parameter as it looks like. But there is also the optional parameter event_id.
`def set_target_battery_soc(self, target_soc: TargetBatteryCode, vin_info: VinInfo, event_id: str = None)`

I think a dedicated method is required for this. Something like
`def set_target_battery_soc_with limited_current(self, target_soc: TargetBatteryCode, vin_info: VinInfo, charge_current_limit , event_id: str = None)`

There is something in the client library needed. If I just merge your code as it is, it will definetly not work.

**Comment by tosate** [comment]
Okay, I see. The missing client code is in @nanomad's fork of the client library

**Comment by nanomad** [comment]
@tosate Ive chatted with @magior on telegram, I'll rebase this pr on top of the current 0.3.0 this weekend.

**Comment by magior** [comment]
Hi, 

Yes, this is to control charge speed during charging.
By mistake, I sent the PR to the official repo. 

I've already sent a pull request to the @nanomad repo for both client and gateway because I use a lot of his code still not merged.

**Comment by tosate** [comment]
Should I reject this pull request since it will be part of a future pull request from @nanomad?

**Comment by nanomad** [comment]
Yep

**Pull request closed without merging**
